chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="chat_home"),
    path("new/", views.start_conversation, name="start_conversation"),
    path("<int:chat_id>/", views.view_chat, name="view_chat"),
    path("<int:chat_id>/delete/", views.delete_chat, name="delete_chat"),


]

demo/urls.py
from django.contrib import admin
from django.urls import path, include

import tasks.views
from demo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("<str:owner>/<str:repo>/pull-request-manager/", include("pr_manager.urls")),
    path("<str:owner>/<str:repo>/tasks/", include("tasks.urls")),
    path("<str:owner>/<str:repo>/reports/", include("reports.urls")),
    path("", views.suite_overview, name="suite_overview"),
]

repositories/urls.py
from django.urls import path
from . import views

app_name = 'repositories'

urlpatterns = [
    path('', views.repo_overview, name='repo_overview'),
    path('select/', views.show_repo_picker, name='show_repo_picker'),
    path('search/', views.find_repositories, name='find_repositories'),
    path('install/<str:owner_name>/<str:repo_name>/', views.install_repo, name='install_repo'),
    path('orgs/<str:owner_name>/repos/<str:repo_name>/bookmark/', views.bookmark_repo, name='bookmark_repo'),
    path('orgs/<str:owner_name>/repos/<str:repo_name>/unbookmark/', views.unbookmark_repo, name='unbookmark_repo'),
]

studio/urls.py
from allauth.socialaccount.providers.github.views import oauth2_login
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from studio import views
from studio.views import health_check

all_patterns = [
    # Redirect default account login to GitHub login URL
    path(
        "accounts/login/",
        RedirectView.as_view(
            url=f"{settings.ROOT_PATH}/github/login/?process=login", permanent=True
        ),
    ),
    path("", views.studio_home, name="studio_home"),
    path("home/<str:owner>/<str:repo>/", views.studio_home, name="studio_home_repo"),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path("pull-request-manager/", include("pr_manager.urls")),
    path("tasks/", include("tasks.urls")),
    path("user/", include("users.urls")),
    path("chat/", include("chat.urls")),
    path("repositories/", include("repositories.urls")),
    path("build/", include("build.urls")),
    path("contribute/", views.contribute, name="contribute"),
    path("login/", oauth2_login, name="github_login"),
    path("logout/", views.user_logout, name="user_logout"),
    path("terms-of-service/", views.terms_of_service, name="terms_of_service"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("code-policy/", views.code_policy, name="code_policy"),
    path("how-it-works/", views.how_it_works, name="how_it_works"),

]

if settings.ROOT_PATH == '/':
    urlpatterns = [
        path("", include(all_patterns)),
        path("healthz/", health_check, name="health_check"),
    ]
else:
    urlpatterns = [
        path("", health_check, name="health_check_root"),
        path("healthz/", health_check, name="health_check"),
        path('studio/', include(all_patterns)),
    ]

repositories/models.py
from django.db import models


class BookmarkedRepo(models.Model):
    owner = models.CharField(max_length=255)
    repo_name = models.CharField(max_length=255)
    user = models.ForeignKey("users.StudioUser", on_delete=models.CASCADE)
    img_url = models.CharField(max_length=255, blank=True, null=True)

    @property
    def full_name(self):
        return f"{self.owner}/{self.repo_name}"

    def __str__(self):
        return f"{self.owner}/{self.repo_name}"

repositories/views.py
from arcane.engine import ArcaneEngine
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from github import Github, UnknownObjectException

from studio.decorators import needs_api_key
from studio.github import get_github_token
from .models import BookmarkedRepo

PAGE_SIZE = 10


def render_paginated_repo_picker(request, repos, repo_count, search_query=None):
    page_count = int(repo_count / PAGE_SIZE) + 1
    page = int(request.GET.get('page', 1))

    if page_count <= 8:
        page_buttons = range(2, page_count - 1)
    else:
        if page == 1:
            page_buttons = [2, 3, 4]
        elif page == page_count:
            page_buttons = [page - 3, page - 2, page - 1]
        elif page == 2:
            page_buttons = [2, 3, 4]
        elif page == page_count - 1:
            page_buttons = [page - 2, page - 1, page]
        else:
            page_buttons = [page - 1, page, page + 1]

    repo_list = repos.get_page(page - 1)
    existing_bookmarks = BookmarkedRepo.objects.filter(user=request.user)
    # Filter out already bookmarked repos
    repo_list = [repo for repo in repo_list if repo.full_name not in [bookmark.full_name for bookmark in existing_bookmarks]]

    return render(request, 'repositories/repo_picker.html', {
        'search_query': search_query,
        'repositories': repo_list,
        'total_page_count': page_count,
        'current_page': page,
        'page_buttons': page_buttons,
        'prev_page': page - 1,
        'next_page': page + 1,
    })


@login_required
def show_repo_picker(request):
    g = Github(get_github_token(request), per_page=PAGE_SIZE)
    github_user = g.get_user()

    repos = github_user.get_repos(sort='pushed', direction='desc', type='owner')
    repos_count = repos.totalCount

    return render_paginated_repo_picker(request, repos, repos_count)


@login_required
@needs_api_key
def repo_overview(request, api_key=None):
    return render_with_repositories(request, 'repositories/overview.html', {
        'active_app': 'bookmarks',
    })


@login_required
@needs_api_key
def bookmark_repo(request, owner_name, repo_name, api_key=None):
    BookmarkedRepo.objects.update_or_create(
        owner=request.POST.get('repo_owner'),
        repo_name=request.POST.get('repo_name'),
        img_url=request.POST.get('img_url'),
        user=request.user)
    engine = ArcaneEngine(api_key)
    if not engine.is_repository_installed(request.POST.get('repo_owner'), request.POST.get('repo_name')):
        return redirect('https://github.com/apps/arcane-engine/installations/new')
    return redirect('repositories:repo_overview')


@login_required
def unbookmark_repo(request, owner_name, repo_name):
    BookmarkedRepo.objects.filter(owner=owner_name, repo_name=repo_name, user=request.user).delete()
    return redirect('repositories:repo_overview')


@login_required
def install_repo(request, owner_name, repo_name):
    try:
        bookmark = BookmarkedRepo.objects.get(owner=owner_name, repo_name=repo_name, user=request.user)
    except BookmarkedRepo.DoesNotExist:
        return render(request, "error.html", {"error": "Repository not found"})
    return render(request, "repositories/install_repo.html", {
        "repo": bookmark,
        "active_app": "bookmarks",
    })


def render_with_repositories(request, template_name, context, org=None, repo_name=None):
    repos = BookmarkedRepo.objects.filter(user=request.user)
    if len(repos) == 0 and template_name != 'repositories/overview.html':
        return redirect('repositories:repo_overview')
    bookmarked_repos_by_owner = {}
    for repo in repos:
        if repo.owner not in bookmarked_repos_by_owner:
            bookmarked_repos_by_owner[repo.owner] = []
        bookmarked_repos_by_owner[repo.owner].append(repo)
        if repo.owner == org and repo.repo_name == repo_name:
            context['selected_repo'] = repo

    if len(repos) > 0:
        if not org:
            org = repos[0].owner
        if not repo_name:
            repo_name = repos[0].repo_name
            context['selected_repo'] = repos[0]
    context['bookmarked_repos'] = bookmarked_repos_by_owner
    context['repo_owner'] = org
    context['repo_name'] = repo_name
    context['total_repo_count'] = len(repos)
    return render(request, template_name, context)


@login_required
def find_repositories(request):
    """Find Github repositories for the user."""
    g = Github(get_github_token(request), per_page=PAGE_SIZE)

    search_query = request.GET.get('query').replace(' ', '+').strip()
    if not search_query:
        return redirect('repositories:show_repo_picker')
    # First, try to see if the search query is a full repo name
    try:
        repo = g.get_user(request.user.username).get_repo(search_query)
        return render(request, 'repositories/repo_picker.html', {
            'search_query': search_query,
            'repositories': [repo],
            'total_page_count': 1,
            'current_page': 1,
            'page_buttons': [],
            'prev_page': 1,
            'next_page': 1,
        })
    except UnknownObjectException as e:
        # Repo not found, let's see if it's an org
        try:
            org = g.get_organization(search_query)
            repos = org.get_repos()
            return render_paginated_repo_picker(request, repos, repos.totalCount, search_query)
        except UnknownObjectException as e:
            # Not an org either, let's search for the query
            results = g.search_repositories(search_query, sort='updated', order='desc')
            return render_paginated_repo_picker(request, results, results.totalCount, search_query)

repositories/templates/repositories/install_repo.html
{% extends 'base.html' %}

{% block content %}
    <section class="hero is-medium">
        <div class="hero-body">
            <p class="title">Permission Required</p>
            <p class="subtitle">The engine needs permission to access <code>{{ repo.owner }} / {{ repo.repo_name }}</code></p>
            <p>
                The Arcane Engine needs permission to access your code, issues, pull requests, and other data in this repository.
            </p>
            <p class="mt-5">
                {% url 'studio_home_repo' owner=repo.owner repo=repo.repo_name as studio_url %}
                <a href="https://github.com/apps/arcane-engine/installations/new?redirect_uri={{ request.scheme }}%3A//{{ request.get_host }}{{ studio_url|urlencode }}" class="button is-shadowless">Grant Permission</a>
            </p>
        </div>
    </section>


{% endblock %}

repositories/templates/repositories/overview.html
{% extends 'base_repos.html' %}

{% block extra_navbar_left %}
{% endblock %}

{% block app_subtitle %}
    {%  if total_repo_count > 1 %}
    Bookmarked Repositories
    {% endif %}
{% endblock %}

{% block repo_content %}


    {%  if not bookmarked_repos|length %}
        <section class="section">

        <div class="content">
            <p class="is-size-5 mb-5">

                <span>Your Github account has been successfully linked to the Arcane Engine.</span>
            </p>
            <p class="is-size-5 mb-5">
                {% url 'repositories:repo_overview' as bookmarks_url %}
                Next, pick the repositories you'd like to work with. Make sure that you've
                <a href="https://github.com/apps/arcane-engine/installations/new?redirect_uri={{ request.scheme }}%3A//{{ request.get_host }}{{ bookmarks_url|urlencode }}">granted permission</a> on Github
                for the engine to access your code, issues and pull requests.
            </p>
            </p>
            <p class="is-size-5 has-text-weight-light mb-5">
                <a href="{% url 'repositories:show_repo_picker' %}" class="button is-medium is-page-loader is-shadowless">Select Repositories</a>
            </p>
        </div>
        </section>
    {% else %}
        {%  if total_repo_count == 1 %}
            <section class="section">
                <p class="is-size-5">
                    <span class="icon has-text-success"><i class="fas fa-check"></i></span>
                    <span>Setup Complete! What would you like to do first?</span>
                </p>
                <div class="buttons my-5">
                    <a class="button is-page-loader is-shadowless is-link" href="{% url 'repositories:show_repo_picker' %}">
                        <span class="icon"><i class="fas fa-plus"></i></span>
                        <span>Add another repository</span>
                    </a>
                    <a class="button is-page-loader is-shadowless" href="{% url 'pr_manager_home' %}">
                        <span class="icon"><i class="fas fa-code-branch"></i></span>
                        <span>Work on a pull request</span>
                    </a>
                    <a class="button is-page-loader is-shadowless" href="{% url 'chat_home' %}">
                        <span class="icon"><i class="fas fa-comments"></i></span>
                        <span>Start a chat</span>
                    </a>
                    <a class="button is-page-loader is-shadowless" href="{% url 'tasks_home' %}">
                        <span class="icon"><i class="fas fa-play"></i></span>
                        <span>Run a task</span>
                    </a>
                </div>

            </section>

        {% else %}
            <div class="table-container">
                <table class="table ">
                    <tbody>
                    {% for owner, bookmarks in bookmarked_repos.items %}
                        {% for bookmark in bookmarks %}
                            <tr class="is-size-5">

                                <td class="is-narrow">
                                    <figure class="image is-24x24 mt-1 has-circle">
                                        <img
                                                src="{{ bookmark.img_url }}"
                                                class="is-rounded" />
                                    </figure>
                                </td>
                                <td class="is-narrow">
                                    {{ bookmark.owner }} / {{ bookmark.repo_name }}
                                </td>
                                <td class="is-narrow">
                                    <a href="{% url 'start_conversation' %}" class="button is-small is-page-loader is-ghost">
                                        <span class="icon"><i class="fas fa-comment"></i></span>
                                    </a>
                                    <a href="{% url 'list_tasks' owner=bookmark.owner repo=bookmark.repo_name %}" class="button is-small is-page-loader is-ghost">
                                        <span class="icon"><i class="fas fa-gears"></i></span>
                                    </a>
                                    <a href="{% url 'view_pull_request_default' owner=bookmark.owner repo=bookmark.repo_name %}" class="button is-small is-page-loader is-ghost">
                                        <span class="icon"><i class="fas fa-code-branch"></i></span>
                                    </a>
                                    <a href="{% url 'build_overview' owner=bookmark.owner repo=bookmark.repo_name %}" class="button is-small is-page-loader is-ghost">
                                        <span class="icon"><i class="fas fa-hammer"></i></span>
                                    </a>
                                </td>
                                <td class="is-narrow">
                                    <a href="https://github.com/{{ bookmark.full_name }}"
                                       class="button is-small is-page-loader is-ghost"
                                       target="_blank">
                                        <span class="icon"><i class="fas fa-arrow-up-right-from-square"></i></span>
                                    </a>
                                </td>
                                <td class="is-flex">
                                    <a class="button is-danger is-small is-ghost has-text-danger is-page-loader"
                                       href="{% url 'repositories:unbookmark_repo' owner_name=owner repo_name=bookmark.repo_name %}">
                                        <span class="icon"><i class="fas fa-trash"></i></span>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <p>
                <a class="button is-page-loader is-link is-small" href="{% url 'repositories:show_repo_picker' %}">
                    <span class="icon"><i class="fas fa-plus"></i></span>
                    <span>Add Repository</span>
                </a>
            </p>
        {% endif %}



    {% endif %}

{% endblock %}

repositories/templates/repositories/repo_picker.html
{% extends 'base.html' %}

{% block content %}

<div class="modal is-active">
    <div class="modal-background"></div>
    <div class="modal-content">
        <nav class="panel is-inline-block has-background-white">
            <p class="panel-heading">
                <span class="icon"><i class="fab fa-github"></i></span>
                Add Repositories
            </p>
            <div class="panel-block">
                <div class="field has-addons">
                    <div class="control has-icons-left">
                        <input class="input" type="text" name="query" placeholder="owner / repo" value="{% if search_query %}{{ search_query }}{% endif %}" />
                        <span class="icon is-left"><i class="fas fa-search" aria-hidden="true"></i></span>
                    </div>
                    <div class="control">
                        <button class="button is-link" id="search-button">
                            Search
                        </button>
                    </div>
                </div>
            </div>

            {# Pagination #}

            <div class="panel-block {% if total_page_count <= 1 %}is-hidden{% endif %}">
                <nav class="pagination is-small" role="navigation" aria-label="pagination">
                    <a href="?page={{ prev_page }}{% if search_query %}&query={{ search_query }}{% endif %}" class="pagination-previous is-page-loader">Previous</a>
                    <a href="?page={{ next_page }}{% if search_query %}&query={{ search_query }}{% endif %}" class="pagination-next is-page-loader">Next page</a>
                    <ul class="pagination-list">
                        <li><a href="?page=1{% if search_query %}&query={{ search_query }}{% endif %}" class="pagination-link is-page-loader {% if current_page == 1 %}is-current{% endif %}" aria-label="Goto page 1">1</a></li>

                        {% if total_page_count < 8 %}
                        {% for middle_page in page_buttons %}
                        <li>
                            <a href="?page={{ middle_page }}{% if search_query %}&query={{ search_query }}{% endif %}"
                               class="pagination-link is-page-loader {% if current_page == middle_page %}is-current{% endif %}"
                               aria-label="Goto page {{ middle_page }}">
                                {{ middle_page }}
                            </a>
                        </li>
                        {% endfor %}
                        {% else %}
                        <li><span class="pagination-ellipsis">&hellip;</span></li>
                        {% for middle_page in page_buttons %}
                        <li>
                            <a href="?page={{ middle_page }}{% if search_query %}&query={{ search_query }}{% endif %}"
                               class="pagination-link is-page-loader {% if current_page == middle_page %}is-current{% endif %}"
                               aria-label="Goto page {{ middle_page }}">
                                {{ middle_page }}
                            </a>
                        </li>
                        {% endfor %}
                        <li><span class="pagination-ellipsis">&hellip;</span></li>
                        {% endif %}

                        <li><a href="?page={{ total_page_count }}{% if search_query %}&query={{ search_query }}{% endif %}" class="pagination-link is-page-loader {% if current_page == total_page_count %}is-current{% endif %}" aria-label="Goto page {{ total_page_count }}">{{ total_page_count }}</a></li>
                    </ul>
                </nav>
            </div>

            {# List of repos for the selected org #}
            {% for repo in repositories %}
            <span class="panel-block">

                <form action="{% url 'repositories:bookmark_repo' repo.owner.login repo.name %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="repo_name" value="{{ repo.name }}" />
                    <input type="hidden" name="repo_owner" value="{{ repo.owner.login }}" />
                    <input type="hidden" name="img_url" value="{{ repo.owner.avatar_url }}" />
                    <button type="submit" class="is-small button is-link mr-3" aria-label="Add Repo">
                        <span class="icon"><i class="fas fa-plus"></i></span>
                    </button>
                </form>

                <figure class="image is-24x24 mr-2">
                  <img
                          src="{{ repo.owner.avatar_url }}"
                          alt="{{ repo.owner.login }}"
                          class="is-rounded" />
                </figure>

                <span>
                    {{ repo.owner.login }} / {{ repo.name }}
                </span>

            </span>

            {% endfor %}

            {% if not repositories %}

            <div class="panel-block">
                <p class="has-text-centered">No repositories found.</p>
            </div>

            {% endif %}
            <div class="panel-block">
                <p class="is-size-7 has-text-grey">To see your private repositories,
                    <a href="https://github.com/apps/arcane-engine/installations/new?redirect_uri={{ request.build_absolute_uri|urlencode }}">grant permission</a> on Github</p>
            </div>

            <div class="panel-block">
                <a class="button is-dark is-outlined is-fullwidth" href="{% url 'repositories:repo_overview' %}">
                    Close
                </a>
            </div>
        </nav>

    </div>

</div>


    <script>
        $(document).ready(function() {
            const searchButton = $('#search-button');

            function search() {
                var query = $('input[name="query"]').val();
                searchButton.addClass('is-loading').attr('disabled', 'disabled');
                window.location.href = "{% url 'repositories:find_repositories' %}?query=" + query;
            }

            searchButton.click(search);

            $(document).on('keypress', function(e) {
                if (e.which === 13) { // 13 is the key code for ENTER
                    search();
                }
            });
        });
    </script>

{% endblock %}