chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="chat_home"),
    path("new/", views.start_conversation, name="start_conversation"),
    path("<int:chat_id>/", views.view_chat, name="view_chat"),
    path("<int:chat_id>/delete/", views.delete_chat, name="delete_chat"),


]

demo/urls.py
from django.contrib import admin
from django.urls import path, include

import tasks.views
from demo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("<str:owner>/<str:repo>/pull-request-manager/", include("pr_manager.urls")),
    path("<str:owner>/<str:repo>/tasks/", include("tasks.urls")),
    path("<str:owner>/<str:repo>/reports/", include("reports.urls")),
    path("", views.suite_overview, name="suite_overview"),
]

repositories/urls.py
from django.urls import path
from . import views

app_name = 'repositories'

urlpatterns = [
    path('', views.repo_overview, name='repo_overview'),
    path('select/', views.show_repo_picker, name='show_repo_picker'),
    path('search/', views.find_repositories, name='find_repositories'),
    path('install/<str:owner_name>/<str:repo_name>/', views.install_repo, name='install_repo'),
    path('orgs/<str:owner_name>/repos/<str:repo_name>/bookmark/', views.bookmark_repo, name='bookmark_repo'),
    path('orgs/<str:owner_name>/repos/<str:repo_name>/unbookmark/', views.unbookmark_repo, name='unbookmark_repo'),
]

studio/urls.py
from allauth.socialaccount.providers.github.views import oauth2_login
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from studio import views
from studio.views import health_check

all_patterns = [
    # Redirect default account login to GitHub login URL
    path(
        "accounts/login/",
        RedirectView.as_view(
            url=f"{settings.ROOT_PATH}/github/login/?process=login", permanent=True
        ),
    ),
    path("", views.studio_home, name="studio_home"),
    path("home/<str:owner>/<str:repo>/", views.studio_home, name="studio_home_repo"),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path("pull-request-manager/", include("pr_manager.urls")),
    path("tasks/", include("tasks.urls")),
    path("user/", include("users.urls")),
    path("chat/", include("chat.urls")),
    path("repositories/", include("repositories.urls")),
    path("build/", include("build.urls")),
    path("contribute/", views.contribute, name="contribute"),
    path("login/", oauth2_login, name="github_login"),
    path("logout/", views.user_logout, name="user_logout"),
    path("terms-of-service/", views.terms_of_service, name="terms_of_service"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("code-policy/", views.code_policy, name="code_policy"),
    path("how-it-works/", views.how_it_works, name="how_it_works"),

]

if settings.ROOT_PATH == '/':
    urlpatterns = [
        path("", include(all_patterns)),
        path("healthz/", health_check, name="health_check"),
    ]
else:
    urlpatterns = [
        path("", health_check, name="health_check_root"),
        path("healthz/", health_check, name="health_check"),
        path('studio/', include(all_patterns)),
    ]

templates/app_header.html
<div class="{% if classes %}{{ classes }}{% else %}mb-3{% endif %} mt-3">
    <p class="title is-size-4 has-text-weight-medium has-text-grey">
        {{ subtitle }}
    </p>
</div>

templates/base.html
{% load static %}
{% load socialaccount %}
{% load i18n %}
{% load allauth %}

<!DOCTYPE html>
<html lang="en" class="has-background-white" data-theme="light">
<head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-1PVNMNEWKS"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-1PVNMNEWKS');
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Arcane Studio{% endblock %}</title>

    <link rel="shortcut icon" type="image/png" href="{% static 'img/orb.png' %}"/>

    <!-- Meta tags -->
    <meta name="description" content="{{ description }}">
    <meta name="keywords" content="LLM,AI,Machine Learning,Developer Tools,Productivity,{{ keywords }}">
    <meta name="author" content="Arcane Engineering">
    <meta name="robots" content="index, follow">
    <meta name="revisit-after" content="1 day">
    <meta name="language" content="English">


    <!-- Social media tags -->
    <meta property="og:title" content="{{ title }}">
    <meta property="og:description" content="{{ description }}">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'img/orb.png' %}">

    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css"
    >
    <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Stylesheet -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github.min.css" />

    <!-- Javascripts -->
    <script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/highlight.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/markdown-it@14.1.0/dist/markdown-it.min.js"></script>

    <script>
        window.md = markdownit({
            highlight: function (str, lang) {
                if (lang && hljs.getLanguage(lang)) {
                    try {
                        return hljs.highlight(str, { language: lang }).value;
                    } catch (__) {}
                }

                return ''; // use external default escaping
            }
        });
    </script>
    <style>



        .laptop {
            border: 7px solid #333; /* Bezel border color */
            border-radius: 20px; /* Rounded corners for the bezel */
            padding: 0px;
            background-color: #222; /* Inner bezel color */
            box-shadow: 0px 10px 30px rgba(0, 0, 0, 0.3); /* Shadow for a 3D effect */
            margin: 50px auto;
            position: relative;
        }

        .laptop::before {
            content: '';
            position: absolute;
            bottom: -20px;
            left: 50%;
            transform: translateX(-50%);
            width: 300px;
            height: 20px;
            background-color: #333;
            border-radius: 0 0 20px 20px;
        }

        .laptop video {
            width: 100%;
            height: 100%;
            display: block;
            border-radius: 10px;
        }
        .tiny-rounded {
            border: 1px solid rgb(228, 228, 228); /* Thin grey border */
            border-radius: 5px;     /* Small rounded corners */
        }
        .has-no-background {
            background-color: transparent !important;
        }
        /* Ensure the body takes the full height of the viewport */
        html, body {
            height: 100%;
            margin: 0;
        }
        /* Flexbox layout for the page */
        .page-container {
            display: flex;
            flex-direction: column;
            min-height: 100vh; /* Ensures the container fills the viewport */
        }
        /* Make the main content take up available space */
        .content-wrap {
            flex: 1; /* Takes up all available space above the footer */
        }
        .has-circle {
            border-radius: 50%;
            border: 1px solid rgb(143, 143, 143); /* Thin grey border */
        }
        .is-blinking {
            animation: blinkAnimation 2s infinite;
        }

        @keyframes blinkAnimation {
            0%   { opacity: 1; }
            50%  { opacity: 0.3; }
            100% { opacity: 1; }
        }

        .has-round-corners {
            border-radius: 8px;
        }

        {% block css %}
        {% endblock %}

    </style>
    {% block extra_header %}{% endblock %}

    <script>
        $(document).ready(function() {
            $('.is-page-loader').click(function() {
                $(this).addClass('is-loading').attr('disabled', 'disabled');
            });
        });
    </script>
</head>
<body class="has-background-white">


<div class="page-container container is-fullwidth">

    {% block navbar %}
    <nav class="navbar my-3" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            {% if repo_name %}
            <a class="navbar-item" href="{% url 'studio_home_repo' owner=repo_owner repo=repo_name %}">
            {% else %}
                <a class="navbar-item" href="{% url 'studio_home' %}">
            {% endif %}
            <span class="button is-page-loader is-shadowless {% if active_app == 'home' %}is-dark{% endif %}">
                <span class="icon"><i class="fas fa-home"></i></span>
            </span>
            </a>

            <!-- Hamburger menu button -->
            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <!-- Navbar items -->
            <div class="navbar-start">


                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-item">
                        <span class="button is-shadowless">
                        {% if active_app == "pull-request-manager" %}
                            <span class="icon"><i class="fas fa-code-branch"></i></span>
                            <span>Pull Requests</span>
                        {% elif active_app == "chat" %}
                            <span class="icon"><i class="fas fa-comment"></i></span>
                            <span>Chat</span>
                        {% elif active_app == "tasks" %}
                            <span class="icon"><i class="fas fa-gears"></i></span>
                            <span>Tasks</span>
                        {% elif active_app == "build" %}
                            <span class="icon"><i class="fas fa-hammer"></i></span>
                            <span>Build</span>
                        {% else %}
                            <span class="icon"><i class="fas fa-cube"></i></span>
                            <span>Select a tool</span>
                        {% endif %}
                        </span>

                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item is-page-loader" href="{% url 'pr_manager_home' %}">
                            <span class="icon"><i class="fas fa-code-branch"></i></span>
                            <span>Pull Requests</span>
                        </a>
                        <a class="navbar-item is-page-loader" href="{% url 'chat_home' %}">
                            <span class="icon"><i class="fas fa-comment"></i></span>
                            <span>Chat</span>
                        </a>
                        <a class="navbar-item is-page-loader" href="{% url 'tasks_home' %}">
                            <span class="icon"><i class="fas fa-gears"></i></span>
                            <span>Tasks</span>
                        </a>
                        <a class="navbar-item is-page-loader" href="{% url 'build_home' %}">
                            <span class="icon"><i class="fas fa-hammer"></i></span>
                            <span>Build</span>
                        </a>
                    </div>
                </div>
                {% block extra_navbar_left %}{% endblock %}
                {% block app_subtitle_navbar_item %}
                <h3 class="navbar-item is-size-4 has-text-grey">
                    {% block app_subtitle %}{% endblock %}
                </h3>
                {% endblock %}
            </div>

            <!-- Navbar end -->
            <div class="navbar-end">

                <div class="navbar-item">
                    <a class="button is-page-loader is-shadowless {% if active_app == 'bookmarks' %}is-dark{% endif %}" href="{% url 'repositories:repo_overview' %}">
                        <span class="icon"><i class="fas fa-bookmark"></i></span>
                    </a>
                </div>
                <div class="navbar-item">
                    <a class="button is-page-loader is-shadowless" href="{% url 'contribute' %}">
                        <span class="icon"><i class="fas fa-info"></i></span>
                    </a>
                </div>
                <div class="navbar-item">
                    {% if user.is_authenticated %}
                        <a href="{% url 'user_profile' %}">
                            <figure class="image has-circle is-32x32">
                                <img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" alt="{{ user.username }}" class="is-rounded" />
                            </figure>
                        </a>
                    {% else %}
                        <a class="button is-rounded is-shadowless" href="{% url 'github_login' %}?next={% url 'studio_home' %}">
                            <span class="icon"><i class="fab fa-github"></i></span>
                            <span>Login</span>
                        </a>
                    {% endif %}
                </div>
                
            </div>
        </div>
    </nav>
    {% endblock %}


    <div class="content-wrap container">
        {% block content %}{% endblock %}
    </div>
    <hr/>

    <footer class="footer has-text-grey has-background-white">
        <div class="columns">
            <div class="column is-three-fifths">
                <p class="title is-5 has-text-grey">
                    <span class="icon"><i class="fas fa-cube"></i></span>
                    <span>Arcane Studio</span>
                </p>
                <p>
                    Copyright © 2024 <a href="https://arcane.engineer" target="_blank">Arcane Engineering</a>. All Rights Reserved.
                </p>
            </div>
            <div class="column">
                <p class="title is-6 has-text-grey">
                    About
                </p>
                <p>
                    <a href="https://arcane.engineer/engine" class="has-text-grey" target="_blank">Arcane Engine</a>
                </p>
                <p>
                    <a href="https://arcane.engineer/pricing" class="has-text-grey" target="_blank">Pricing</a>
                </p>
                <p>
                    <a href="https://docs.arcane.engineer" class="has-text-grey" target="_blank">Documentation</a>
                </p>
                <p>
                    <a href="mailto:support@arcane.engineer" class="has-text-grey">Support</a>
                </p>
            </div>
            <div class="column">
                <p class="title is-6 has-text-grey">
                    Legal
                </p>
                <p>
                    <a href="https://arcane.engineer/studio/code-policy/" class="has-text-grey" >Code Policy</a>
                </p>
                <p>
                    <a href="https://arcane.engineer/studio/privacy-policy/" class="has-text-grey" >Privacy Policy</a>
                </p>
                <p>
                    <a href="https://arcane.engineer/studio/terms-of-service/" class="has-text-grey" >Terms of Service</a>
                </p>
            </div>
        </div>
    </footer>
</div>

<script>
    $(document).ready(function() {
        // Toggle the navbar menu when the burger is clicked
        $(".navbar-burger").click(function() {
            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            $(this).toggleClass("is-active");
            var target = $(this).data("target");
            $("#" + target).toggleClass("is-active");
        });
    });
</script>


</body>
</html>

templates/base_repos.html
{% extends 'base.html' %}

{% block extra_navbar_left %}



<div class="navbar-item">
    {% url 'contribute' as contribute_url %}
    <div class="control has-icons-left">
        <div class="select">
            <select name="repo_id" id="repo-selector">
                <option value="" disabled>Select a repository</option>
                {% for owner, repos in bookmarked_repos.items %}
                    {% for bookmark in repos %}
                        {% if active_app == "tasks" %}
                            {% url 'list_tasks' owner=bookmark.owner repo=bookmark.repo_name as repo_link %}
                        {% elif active_app == "pull-request-manager" %}
                            {% url 'view_pull_request_default' owner=bookmark.owner repo=bookmark.repo_name as repo_link %}
                        {% elif active_app == "reports" %}
                            {% url 'view_reports' owner=bookmark.owner repo=bookmark.repo_name as repo_link %}
                        {% elif active_app == "build" %}
                            {% url 'build_overview' owner=bookmark.owner repo=bookmark.repo_name as repo_link %}
                        {% elif active_app == "home" %}
                            {% url 'studio_home_repo' owner=bookmark.owner repo=bookmark.repo_name as repo_link %}
                        {% else %}
                            {% url 'list_tasks' owner=bookmark.owner repo=bookmark.repo_name as repo_link %}
                        {% endif %}

                        <option data-url="{{ repo_link }}"
                                value="{{ bookmark.full_name }}"
                                {% if bookmark.owner == repo_owner and bookmark.repo_name == repo_name %}selected{% endif %}>
                            {{ bookmark.owner }} / {{ bookmark.repo_name }}
                        </option>
                    {% endfor %}
                {% endfor %}
            </select>
        </div>
        <span class="icon is-left">
    <i class="fab fa-github"></i>
  </span>
    </div>

</div>
{% endblock %}

{% block content %}



    {% block repo_content %}

    {% endblock %}
    <script>
    $(document).ready(function() {
        $('.repo-menu-item').click(function() {
            $(this).addClass('is-unselectable').attr('disabled', 'disabled');
        });
        $('#repo-selector').on('change', function() {
            $(this).attr('disabled', 'disabled');
            const url = $(this).find(':selected').data('url');
            if (url) {
                console.log(url);
                window.location.href=url;
            }
        });

    });
    </script>

{% endblock %}

templates/central.html
{% extends "base_repos.html" %}

{% block title %}Arcane Studio{% endblock %}

<p class="title is-1">
    Home
</p>
<p class="subtitle is-3">
    Welcome to Arcane Studio
</p>

{% block repo_content %}

    <section class="section content">
        <p class="title is-1">
            Arcane Studio
        </p>
        <p class="subtitle is-3">
            <code>
                <span class="icon"><i class="fab fa-github"></i></span>
                {{ repo_owner }} / {{ repo_name }}
            </code>
        </p>
        <p class="is-size-5">
            This is your dashboard with quick access to the main functionalities of the studio. You can create tasks, start conversations, and
            have quick access to your open pull requests.
        </p>
        <div class="columns">
            <div class="column is-5">
                <!-- Message Form -->
                <div class="">

                    <form method="post" id="taskForm">
                        {% csrf_token %}

                        <div class="field">
                            <div class="control">
                                <textarea class="textarea is-link" name="task_description" placeholder="Provide instructions for a task or start a conversation"></textarea>
                            </div>
                        </div>
                        <div class="field is-grouped">
                            <div class="control">
                                <input type="hidden" name="repo_owner" value="{{ repo_owner }}">
                                <input type="hidden" name="repo_name" value="{{ repo_name }}">
                                <input type="hidden" name="repo_id" value="{{ selected_repo.id }}">
                                <button class="button is-link send-button" type="submit" name="run-task-button" onclick="submitForm('{% url 'create_task' owner=repo_owner repo=repo_name  %}')">
                                    <span class="icon"><i class="fa fa-play"></i></span>
                                    <span>Run a Task</span>
                                </button>
                                <span class="has-text-centered px-2 has-text-weight-light is-size-4">
                                    or
                                </span>
                                <button class="button is-link send-button" type="submit" name="start-conversation-button" onclick="submitForm('{% url 'start_conversation'  %}')">
                                    <span class="icon"><i class="fa fa-comment"></i></span>
                                    <span>Start a Conversation</span>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="column is-7">
                <!-- Pull Requests -->
                {% if pull_requests %}


                    <div class="table-container">
                        <table class="table is-fullwidth">
                            <tbody>
                            {% for pr in pull_requests %}
                                <tr>
                                    <td class="is-narrow">
                                        <a href="{{ pr.html_url }}" target="_blank">#{{ pr.number }}</a>
                                    </td>
                                    <td>
                                        {{ pr.title }}
                                    </td>
                                    <td>
                                        <div class="buttons">
                                            <a class="button is-small is-page-loader is-ghost"
                                               aria-label="PR description"
                                               href="{% url 'view_pull_request' owner=selected_repo.owner repo=selected_repo.repo_name pr_number=pr.number pr_tab='describe' %}">
                                                <span class="icon"><i class="fa fa-file-waveform"></i></span>
                                            </a>
                                            <a class="button is-small is-page-loader is-ghost" href="{% url 'view_pull_request' owner=selected_repo.owner repo=selected_repo.repo_name pr_number=pr.number pr_tab='review' %}">
                                                <span class="icon"><i class="fa fa-magnifying-glass"></i></span>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>


                {% else %}
                    <div class="content is-size-5 has-text-weight-light has-text-centered">
                        <p>No open pull requests</p>
                    </div>
                {% endif %}
            </div>
        </div>
    </section>


    <script>
        function submitForm(actionUrl) {
            const form = document.getElementById('taskForm');
            form.action = actionUrl;
        }

        $('form').on('submit', function() {
            // Disable the button
            $('#send-button').prop('disabled', true);
            // Make the input read-only to prevent further input but allow the form to submit it
            $('textarea[name="message"]').prop('readonly', true);
        });
        $('.send-button').click(function() {
            $(this).addClass('is-loading');
        });
    </script>

{% endblock %}

templates/contribute.html
{% extends "base.html" %}

{%  block css %}
{% endblock %}

{% block content %}
    <section class="hero is-dark has-round-corners">
        <div class="hero-body">
            <div class="container">
                <h1 class="title is-1">
                    <span class="icon is-large"><i class="fas fa-circle-info"></i></span>
                    <span>Feedback & Support</span>
                </h1>
                <h2 class="subtitle is-3">
                    How to contribute and where to find help
                </h2>
            </div>
        </div>
    </section>
<section class="section content is-size-5">
    <p class="title is-4">Extend or Customize Arcane Studio</p>
    <p class="">
        The Arcane Studio is <a href="https://github.com/arc-eng/studio" target="_blank">open-source</a>. We welcome contributions from the community.

        If you're interested in building a tool like this for your own team, check out our <a href="https://arcane.engineer/development-kit" target="_blank" class="has-font-weight-medium">Development Kit</a>.
    </p>
    
    <div class="columns">
        <div class="column is-6">
            <p class="title is-4">Feedback</p>
            <script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/embed/v2.js"></script>
            <script>
                hbspt.forms.create({
                    portalId: "47949042",
                    formId: "e3a0155c-3b37-4b7c-a660-494b7c8577ce"
                });
            </script>
        </div>
        <div class="column is-6">
            <p class="title is-4 mx-5">Support</p>
            <p class="m-5">
                
                If you have any questions or need help, feel free to reach out to us directly at <a href="mailto:support@arcane.engineer" class="has-font-weight-medium">support@arcane.engineer</a> or
                <a href="https://github.com/orgs/arc-eng/discussions">start a discussion on Github</a>.
            </p>
        </div>

    </div>


</section>

{% endblock %}

templates/error.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-half">
                <div class="content is-large">
                    <h1 class="title is-1 has-text-centered">Error</h1>
                    <p class="has-text-centered p-5">
                        {{ error }}
                    </p>
                    <p class="has-text-centered">
                        <a href="{{ request.referrer }}" class="button is-medium">
                            <span class="icon"><i class="fas fa-arrow-left"></i></span>
                            <span>Go back</span>
                        </a>
                    </p>

                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

templates/how_it_works.html
{% extends "base.html" %}

{% block title %}Arcane Studio - How it Works{% endblock %}

{% block content %}
    <section class="hero is-dark has-round-corners">
        <div class="hero-body">
            <div class="container">
                <h1 class="title is-1 is-2-mobile">
                    <span>
                        Your new favorite <span class=""><span class="icon is-large"><i class="fas fa-toolbox"></i></span> tool belt</span>
                    </span>
                </h1>
                <h2 class="subtitle is-3 is-4-mobile">
                    Simple & intuitive prompt-based interfaces
                </h2>
            </div>
        </div>
    </section>


    <section class="section">
        <div class="columns">
            <div class="column is-5-desktop is-6-tablet is-flex is-align-items-center">
                <div class="content ">
                    <p class="is-size-5">
                        At the top of the page you'll find a list of tools, each with a different user experience. Choose the tool that best fits your needs and click on it to get started.

                    </p>
                    <p class="has-text-centered">
                        <a href="{% url 'github_login' %}?next={% url 'repositories:repo_overview' %}" class="button is-link is-large is-fullwidth">
                            <span>Start with 500 free credits</span>
                        </a>
                    </p>

                    <p class="is-size-5">
                        Built using the <a href="https://arcane.engineer/engine/">Arcane Engine Platform</a>, our tools use generative AI to understand
                        natural language prompts. Given a prompt, the engine will use its <a href="https://docs.arcane.engineer/capabilities.html" target="_blank">capabilities</a> to interact with your Github repositories and other data sources like issues, pull requests, wikis and <a href="https://docs.arcane.engineer/integrations.html" target="_blank">more</a>.

                    </p>

                </div>
            </div>
            <div class="column is-7-desktop is-6-tablet">
                <div class="table-container">

                    <table class="table">
                        <tbody>
                        {% for tool in tools %}
                            <tr style="border:none">
                                <td class="is-narrow" style="border:none">
                                    <a href="{{ tool.link }}" class="button is-medium is-fullwidth is-shadowless">
                                        <span class="icon">
                                            <i class="fas {{ tool.icon }}"></i>
                                        </span>
                                        <span>{{ tool.name }}</span>
                                    </a>
                                </td>
                                <td class="is-size-5  is-vcentered" style="border:none">
                                    {{ tool.description}}
                                </td>
                            </tr>
                        {% endfor %}
                        <tr style="border:none">
                            <td class="is-narrow" style="border:none">
                                <a href="{% url 'contribute' %}" class="button is-medium is-fullwidth is-shadowless">
                                        <span class="icon">
                                            <i class="fas fa-user"></i>
                                        </span>
                                    <span>Custom</span>
                                </a>
                            </td>
                            <td class="is-size-5  is-vcentered" style="border:none">
                                Build your own tool using the Arcane Engine <a href="https://arcane.engineer/api/swagger-ui/">API</a> and <a href="https://arcane.engineer/development-kit/">SDK</a>
                            </td>

                        </tr>
                        </tbody>
                    </table>

                </div>
            </div>

        </div>
    </section>


{% endblock %}